platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: movie-service

outputs:
- name: package-output

run:
  path: movie-service/ci/tasks/package.sh
